import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import PageTransition from "@/components/PageTransition";
import { ThemeProvider } from "@/context/ThemeContext";
import dynamic from "next/dynamic";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const GridMotion = dynamic(() =>
    import("@/components/Grid_Motion_Background")
  );

  return (
    <html lang="en">
      <body className="relative overflow-x-hidden">
        <ThemeProvider>
          {/* GRID BACKGROUND NOW INSIDE THEME PROVIDER */}
          <div className="fixed inset-0 -z-10 pointer-events-none">
            <GridMotion />
          </div>

          <div className="relative z-10">
            <PageTransition>
              <Navbar />
              {children}
            </PageTransition>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
